/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Doctor;

/**
 *
 * @author Ma2017
 */
public class ViewOrphanDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrphanDetailJPanel
     */
    public ViewOrphanDetailJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        submitRBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        Icon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NameFID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ShelterFID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SexFID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        weightFID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        doctorFID = new javax.swing.JTextField();
        pharmacyFeedbackFID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DoctorMessFID = new javax.swing.JTextField();
        requestBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        kGradientPanel2.setkEndColor(new java.awt.Color(240, 80, 83));
        kGradientPanel2.setkStartColor(new java.awt.Color(225, 238, 195));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitRBtn.setBackground(new java.awt.Color(195, 55, 100));
        submitRBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitRBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitRBtn.setText("Submit Result");
        submitRBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(submitRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 194, 40));

        backBtn.setBackground(new java.awt.Color(195, 55, 100));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("<<Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 160, 30));

        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_noimage.png"))); // NOI18N
        kGradientPanel2.add(Icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 200, 190));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Name");
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 160, -1));

        NameFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NameFID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(225, 238, 195)));
        kGradientPanel2.add(NameFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 210, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Orphan Shelter");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 160, -1));

        ShelterFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ShelterFID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(225, 238, 195)));
        kGradientPanel2.add(ShelterFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 210, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Sex");
        kGradientPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 160, -1));

        SexFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SexFID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(225, 238, 195)));
        kGradientPanel2.add(SexFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 210, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Race");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 160, -1));

        weightFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        weightFID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(225, 238, 195)));
        kGradientPanel2.add(weightFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 210, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Doctor");
        kGradientPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 160, -1));

        doctorFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doctorFID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(225, 238, 195)));
        kGradientPanel2.add(doctorFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 210, -1));

        pharmacyFeedbackFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pharmacyFeedbackFID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(225, 238, 195)));
        kGradientPanel2.add(pharmacyFeedbackFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 210, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Pharmacy Feedback");
        kGradientPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 160, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Doctor Message");
        kGradientPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 160, -1));

        DoctorMessFID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DoctorMessFID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(225, 238, 195)));
        kGradientPanel2.add(DoctorMessFID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 460, 40));

        requestBtn.setBackground(new java.awt.Color(195, 55, 100));
        requestBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        requestBtn.setForeground(new java.awt.Color(255, 255, 255));
        requestBtn.setText("Request Pahrmaceutical");
        requestBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        requestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBtnActionPerformed(evt);
            }
        });
        kGradientPanel2.add(requestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 194, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Orphan Detail");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitRBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void requestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DoctorMessFID;
    private javax.swing.JLabel Icon;
    private javax.swing.JTextField NameFID;
    private javax.swing.JTextField SexFID;
    private javax.swing.JTextField ShelterFID;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField doctorFID;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField pharmacyFeedbackFID;
    private javax.swing.JButton requestBtn;
    private javax.swing.JButton submitRBtn;
    private javax.swing.JTextField weightFID;
    // End of variables declaration//GEN-END:variables
}
