/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.OrphanManagement;

import Model.EcoSystem.EcoSystem;
import Model.EcoSystem.Network;
import Model.Enterprise.Enterprise;
import Model.Organization.Organization;
import Model.Orphan.Orphan;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.AdoptionRequest;
import Model.WorkQueue.WorkRequest;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alilovepeach
 */
public class AdoptionRequestJPanel extends javax.swing.JPanel {

    EcoSystem ecosys;
    Network network;
    Enterprise enterprise;
    Organization org;
    UserAccount useraccount;
    Orphan orphan;

    /**
     * Creates new form AdoptionRequestJPanel
     */
    public AdoptionRequestJPanel(EcoSystem ecosys, Network network, Enterprise enterprise, Organization org, UserAccount useraccount) {
        initComponents();
        this.ecosys = ecosys;
        this.network = network;
        this.enterprise = enterprise;
        this.org = org;
        this.useraccount = useraccount;

        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimalAdoptionWorkQueue = new javax.swing.JTable();
        btnApproveAdoptionRequest = new javax.swing.JButton();
        btnRejectAdoptionRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setSize(new java.awt.Dimension(800, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(101, 78, 163));
        kGradientPanel1.setkStartColor(new java.awt.Color(234, 175, 200));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(800, 520));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Adoption Request");
        kGradientPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        tblAnimalAdoptionWorkQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Applicant", "Applicant Email", "Organization", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAnimalAdoptionWorkQueue);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, 350));

        btnApproveAdoptionRequest.setText("Approve");
        btnApproveAdoptionRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveAdoptionRequestActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnApproveAdoptionRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 170, 40));

        btnRejectAdoptionRequest.setText("Reject");
        btnRejectAdoptionRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectAdoptionRequestActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnRejectAdoptionRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 170, 40));

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveAdoptionRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveAdoptionRequestActionPerformed

    }//GEN-LAST:event_btnApproveAdoptionRequestActionPerformed

    private void btnRejectAdoptionRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectAdoptionRequestActionPerformed

    }//GEN-LAST:event_btnRejectAdoptionRequestActionPerformed

    public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblAnimalAdoptionWorkQueue.getModel();

        model.setRowCount(0);
        for (WorkRequest request : network.getWorkQueue().getWorkRequestList()) {
            if (request instanceof AdoptionRequest && request.getOrphan() == orphan) {
                Object[] row = new Object[5];
                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getSender().getEmailId();
                row[3] = request.getSender().getOrgainization();
                row[4] = request.getStatus();

                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApproveAdoptionRequest;
    private javax.swing.JButton btnRejectAdoptionRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblAnimalAdoptionWorkQueue;
    // End of variables declaration//GEN-END:variables
}
