/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.OrphanManagement;

/**
 *
 * @author alilovepeach
 */
public class OrphanManagerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form OrphanManagerJFrame
     */
    public OrphanManagerJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAssignOrphan = new javax.swing.JButton();
        btnViewOrphan = new javax.swing.JButton();
        btnViewAdoptionReq = new javax.swing.JButton();
        btnRegOrphan = new javax.swing.JButton();
        btnRequestVolunteer = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(200, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(795, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 236, 236));
        jPanel2.setMinimumSize(new java.awt.Dimension(200, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAssignOrphan.setText("Orphan Assignment");
        btnAssignOrphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignOrphanActionPerformed(evt);
            }
        });
        jPanel2.add(btnAssignOrphan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 220, 190, -1));

        btnViewOrphan.setText("View On Going Orphan");
        jPanel2.add(btnViewOrphan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 270, 190, -1));

        btnViewAdoptionReq.setText("View Adoption Request");
        jPanel2.add(btnViewAdoptionReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 320, 190, -1));

        btnRegOrphan.setText("Register Orphan");
        btnRegOrphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegOrphanActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegOrphan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 120, 190, -1));

        btnRequestVolunteer.setText("Request Volunteer");
        btnRequestVolunteer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestVolunteerActionPerformed(evt);
            }
        });
        jPanel2.add(btnRequestVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 170, 190, -1));

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignOrphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignOrphanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignOrphanActionPerformed

    private void btnRegOrphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegOrphanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegOrphanActionPerformed

    private void btnRequestVolunteerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestVolunteerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestVolunteerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrphanManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrphanManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrphanManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrphanManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrphanManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignOrphan;
    private javax.swing.JButton btnRegOrphan;
    private javax.swing.JButton btnRequestVolunteer;
    private javax.swing.JButton btnViewAdoptionReq;
    private javax.swing.JButton btnViewOrphan;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
