/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.OrphanRegister;

/**
 *
 * @author alilovepeach
 */
public class OrphanRegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrpanRegisterJPanel
     */
    public OrphanRegisterJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        btnSaveAnimal = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        fieldAnimalName = new javax.swing.JTextField();
        lblMessage5 = new javax.swing.JLabel();
        txtAnimalArea = new javax.swing.JTextField();
        lblMessage6 = new javax.swing.JLabel();
        lblMessage7 = new javax.swing.JLabel();
        fieldWeight = new javax.swing.JTextField();
        lblMessage8 = new javax.swing.JLabel();
        lblMessage12 = new javax.swing.JLabel();
        btnUploadAnimalPhoto = new javax.swing.JButton();
        fieldPhoto = new javax.swing.JTextField();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        btnBrowsePhoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 255));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(101, 78, 163));
        kGradientPanel1.setkStartColor(new java.awt.Color(234, 175, 200));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSaveAnimal.setText("Register");
        btnSaveAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAnimalActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSaveAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 100, 30));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblTitle.setText("Register Orphan");
        kGradientPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));
        kGradientPanel1.add(fieldAnimalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 217, -1));

        lblMessage5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage5.setText("Name:");
        kGradientPanel1.add(lblMessage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        kGradientPanel1.add(txtAnimalArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 217, -1));

        lblMessage6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage6.setText("Age:");
        kGradientPanel1.add(lblMessage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        lblMessage7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage7.setText("Sex:");
        kGradientPanel1.add(lblMessage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        fieldWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWeightActionPerformed(evt);
            }
        });
        fieldWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldWeightKeyPressed(evt);
            }
        });
        kGradientPanel1.add(fieldWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 217, -1));

        lblMessage8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage8.setText("Race:");
        kGradientPanel1.add(lblMessage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 40, -1));

        lblMessage12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMessage12.setText("Photo:");
        kGradientPanel1.add(lblMessage12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        btnUploadAnimalPhoto.setText("Upload");
        btnUploadAnimalPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadAnimalPhotoActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnUploadAnimalPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 100, 30));
        kGradientPanel1.add(fieldPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 217, -1));

        buttonGroup1.add(rbtnMale);
        rbtnMale.setSelected(true);
        rbtnMale.setText("Male");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        buttonGroup1.add(rbtnFemale);
        rbtnFemale.setText("Female");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });
        kGradientPanel1.add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        btnBrowsePhoto.setText("browse...");
        kGradientPanel1.add(btnBrowsePhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 200, 200));

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAnimalActionPerformed

    }//GEN-LAST:event_btnSaveAnimalActionPerformed

    private void fieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWeightActionPerformed

    }//GEN-LAST:event_fieldWeightActionPerformed

    private void fieldWeightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldWeightKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWeightKeyPressed

    private void btnUploadAnimalPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadAnimalPhotoActionPerformed

    }//GEN-LAST:event_btnUploadAnimalPhotoActionPerformed

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemaleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowsePhoto;
    private javax.swing.JButton btnSaveAnimal;
    private javax.swing.JButton btnUploadAnimalPhoto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldAnimalName;
    private javax.swing.JTextField fieldPhoto;
    private javax.swing.JTextField fieldWeight;
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblMessage12;
    private javax.swing.JLabel lblMessage5;
    private javax.swing.JLabel lblMessage6;
    private javax.swing.JLabel lblMessage7;
    private javax.swing.JLabel lblMessage8;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTextField txtAnimalArea;
    // End of variables declaration//GEN-END:variables
}
