/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdministrativeRole;

import Model.EcoSystem.EcoSystem;
import Model.UserAccount.UserAccount;

/**
 *
 * @author hp
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    EcoSystem ecosys;
    UserAccount useraccount;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationJPanel() {
        initComponents();
    }

    public ManageOrganizationJPanel(EcoSystem ecosys, UserAccount useraccount) {
        initComponents();
        this.ecosys = ecosys;
        this.useraccount = useraccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOrganizationPicker = new javax.swing.JLabel();
        cmbNetworkList = new javax.swing.JComboBox();
        kGradientPanel = new keeptoo.KGradientPanel();
        lblTitle = new javax.swing.JLabel();
        lblOrganizationList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizations = new javax.swing.JTable();
        lblOrganizationPicker1 = new javax.swing.JLabel();
        cmbEnterpriseList = new javax.swing.JComboBox();
        lblSelectOrgType = new javax.swing.JLabel();
        cmbOrganizations = new javax.swing.JComboBox();
        lblOrganizationName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblOrganizationPicker2 = new javax.swing.JLabel();
        cmbNetworkList1 = new javax.swing.JComboBox();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        lblOrganizationPicker.setText("Select Region:");

        cmbNetworkList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNetworkList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNetworkListActionPerformed(evt);
            }
        });

        setLayout(new java.awt.BorderLayout());

        kGradientPanel.setkEndColor(new java.awt.Color(255, 221, 225));
        kGradientPanel.setkStartColor(new java.awt.Color(238, 156, 167));
        kGradientPanel.setPreferredSize(new java.awt.Dimension(800, 520));
        kGradientPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Manage Organizations");
        kGradientPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        lblOrganizationList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOrganizationList.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganizationList.setText("Organization List:");
        kGradientPanel.add(lblOrganizationList, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        tblOrganizations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Network", "Organization"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganizations);

        kGradientPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 390, 370));

        lblOrganizationPicker1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrganizationPicker1.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganizationPicker1.setText("Select Enterprise:");
        kGradientPanel.add(lblOrganizationPicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        kGradientPanel.add(cmbEnterpriseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 167, -1));

        lblSelectOrgType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSelectOrgType.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectOrgType.setText("Select Organization Type:");
        kGradientPanel.add(lblSelectOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        kGradientPanel.add(cmbOrganizations, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 167, -1));

        lblOrganizationName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrganizationName.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganizationName.setText("Organization Name:");
        kGradientPanel.add(lblOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));
        kGradientPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 169, 26));

        btnAdd.setBackground(new java.awt.Color(238, 156, 167));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Create Organization");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kGradientPanel.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 170, 30));

        lblOrganizationPicker2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOrganizationPicker2.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganizationPicker2.setText("Select Nework:");
        kGradientPanel.add(lblOrganizationPicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, 22));

        cmbNetworkList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNetworkList1ActionPerformed(evt);
            }
        });
        kGradientPanel.add(cmbNetworkList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 167, -1));

        btnUpdate.setBackground(new java.awt.Color(238, 156, 167));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Organization");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        kGradientPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 170, 30));

        btnDelete.setBackground(new java.awt.Color(238, 156, 167));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Organization");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        kGradientPanel.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 170, 30));

        add(kGradientPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNetworkListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetworkListActionPerformed

//        populateEnterpriseCombo();
    }//GEN-LAST:event_cmbNetworkListActionPerformed

    private void cmbNetworkList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNetworkList1ActionPerformed

//        populateEnterpriseCombo();
    }//GEN-LAST:event_cmbNetworkList1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbEnterpriseList;
    private javax.swing.JComboBox cmbNetworkList;
    private javax.swing.JComboBox cmbNetworkList1;
    private javax.swing.JComboBox cmbOrganizations;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel;
    private javax.swing.JLabel lblOrganizationList;
    private javax.swing.JLabel lblOrganizationName;
    private javax.swing.JLabel lblOrganizationPicker;
    private javax.swing.JLabel lblOrganizationPicker1;
    private javax.swing.JLabel lblOrganizationPicker2;
    private javax.swing.JLabel lblSelectOrgType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblOrganizations;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
