/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdministrativeRole;

import Model.EcoSystem.EcoSystem;
import Model.UserAccount.UserAccount;

/**
 *
 * @author hp
 */
public class SysAdminDashboardJPanel extends javax.swing.JPanel {

    EcoSystem ecosys;
    UserAccount useraccount;

    /**
     * Creates new form SysAdminDashboardJPanel
     */
    public SysAdminDashboardJPanel() {
        initComponents();
    }

    public SysAdminDashboardJPanel(EcoSystem ecosys, UserAccount useraccount) {
        initComponents();
        this.ecosys = ecosys;
        this.useraccount = useraccount;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new keeptoo.KGradientPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel_ourService = new javax.swing.JPanel();
        jPanel_adoption = new javax.swing.JPanel();
        jPanel_adoption1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        kGradientPanel3.setkEndColor(new java.awt.Color(255, 221, 225));
        kGradientPanel3.setkStartColor(new java.awt.Color(238, 156, 167));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(800, 520));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Dashboard");
        kGradientPanel3.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 93, -1, -1));

        jPanel_ourService.setBackground(new java.awt.Color(238, 156, 167));
        jPanel_ourService.setLayout(new java.awt.BorderLayout());
        kGradientPanel3.add(jPanel_ourService, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 181, 241, 230));

        jPanel_adoption.setBackground(new java.awt.Color(238, 156, 167));
        jPanel_adoption.setLayout(new java.awt.BorderLayout());
        kGradientPanel3.add(jPanel_adoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 181, 244, 230));

        jPanel_adoption1.setBackground(new java.awt.Color(238, 156, 167));
        jPanel_adoption1.setLayout(new java.awt.BorderLayout());
        kGradientPanel3.add(jPanel_adoption1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 181, 244, 230));

        add(kGradientPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_adoption;
    private javax.swing.JPanel jPanel_adoption1;
    private javax.swing.JPanel jPanel_ourService;
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
