/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Adopter;

/**
 *
 * @author hp
 */
public class AdopterWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdopterWorkAreaJPanel
     */
    public AdopterWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAuthorizationStatus = new javax.swing.JLabel();
        txtAuthorizationStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrphanList = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lblOrphanSelection = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        btnSendRequest = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblAdoptionRequest = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAdoptionRequests = new javax.swing.JTable();

        setBackground(new java.awt.Color(254, 236, 236));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAuthorizationStatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAuthorizationStatus.setForeground(new java.awt.Color(0, 102, 153));
        lblAuthorizationStatus.setText("Authorization Status:");
        add(lblAuthorizationStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
        add(txtAuthorizationStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 45, 163, -1));

        tbOrphanList.setBackground(new java.awt.Color(204, 204, 204));
        tbOrphanList.setForeground(new java.awt.Color(0, 102, 153));
        tbOrphanList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Gender", "Area", "Authority", "Orphan Shelter"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbOrphanList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 560, 110));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 480, 10));

        lblOrphanSelection.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblOrphanSelection.setForeground(new java.awt.Color(0, 102, 153));
        lblOrphanSelection.setText("Orphan Selection:");
        add(lblOrphanSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 104, -1, -1));

        btnViewDetails.setBackground(new java.awt.Color(0, 102, 153));
        btnViewDetails.setForeground(new java.awt.Color(238, 238, 238));
        btnViewDetails.setText("View");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        btnSendRequest.setBackground(new java.awt.Color(0, 102, 153));
        btnSendRequest.setForeground(new java.awt.Color(238, 238, 238));
        btnSendRequest.setText("Adopt");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });
        add(btnSendRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 311, 530, 10));

        lblAdoptionRequest.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAdoptionRequest.setForeground(new java.awt.Color(0, 102, 153));
        lblAdoptionRequest.setText("Your Adoption Request:");
        add(lblAdoptionRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 348, -1, -1));

        tblAdoptionRequests.setBackground(new java.awt.Color(204, 204, 204));
        tblAdoptionRequests.setForeground(new java.awt.Color(0, 102, 153));
        tblAdoptionRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Authority", "Enterprise", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAdoptionRequests);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 560, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed


    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed

    }//GEN-LAST:event_btnSendRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAdoptionRequest;
    private javax.swing.JLabel lblAuthorizationStatus;
    private javax.swing.JLabel lblOrphanSelection;
    private javax.swing.JTable tbOrphanList;
    private javax.swing.JTable tblAdoptionRequests;
    private javax.swing.JTextField txtAuthorizationStatus;
    // End of variables declaration//GEN-END:variables
}
