/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Adopter;

import Model.EcoSystem.EcoSystem;
import Model.EcoSystem.Network;
import Model.Enterprise.Enterprise;
import Model.Organization.Organization;
import Model.UserAccount.UserAccount;

/**
 *
 * @author hp
 */
public class ViewOrphanDetailJPanel extends javax.swing.JPanel {
 EcoSystem ecosys;
    Network network;
    Enterprise enterprise;
    Organization org;
    UserAccount useraccount;
    /**
     * Creates new form ViewOrphanDetailJPanel
     */
    public ViewOrphanDetailJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel3 = new keeptoo.KGradientPanel();
        lblTitle = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblMessage5 = new javax.swing.JLabel();
        txtOrphanfName = new javax.swing.JTextField();
        lblMessage7 = new javax.swing.JLabel();
        txtOrphanAge = new javax.swing.JTextField();
        lblMessage8 = new javax.swing.JLabel();
        lblMessage9 = new javax.swing.JLabel();
        txtOrphanRace = new javax.swing.JTextField();
        lblMessage12 = new javax.swing.JLabel();
        txtOrphanMessageFromDr = new javax.swing.JTextField();
        lblMessage11 = new javax.swing.JLabel();
        txtAnimalMessageFromPharmacy = new javax.swing.JTextField();
        rbtnMale1 = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(247, 183, 51));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        kGradientPanel3.setkEndColor(new java.awt.Color(247, 183, 51));
        kGradientPanel3.setkStartColor(new java.awt.Color(252, 74, 26));
        kGradientPanel3.setPreferredSize(new java.awt.Dimension(800, 520));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText(" Orphan Detail");
        kGradientPanel3.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 37, -1, -1));
        kGradientPanel3.add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 99, 248, 226));

        lblMessage5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage5.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage5.setText("Name:");
        kGradientPanel3.add(lblMessage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 122, -1, -1));

        txtOrphanfName.setEnabled(false);
        kGradientPanel3.add(txtOrphanfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 122, 270, -1));

        lblMessage7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage7.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage7.setText("Age:");
        kGradientPanel3.add(lblMessage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 178, -1, -1));

        txtOrphanAge.setEnabled(false);
        kGradientPanel3.add(txtOrphanAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 178, 270, -1));

        lblMessage8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage8.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage8.setText("Sex:");
        kGradientPanel3.add(lblMessage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        lblMessage9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage9.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage9.setText("Race:");
        kGradientPanel3.add(lblMessage9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        txtOrphanRace.setEnabled(false);
        kGradientPanel3.add(txtOrphanRace, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 270, 29));

        lblMessage12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage12.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage12.setText("Docter Feedback:");
        kGradientPanel3.add(lblMessage12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        txtOrphanMessageFromDr.setEnabled(false);
        kGradientPanel3.add(txtOrphanMessageFromDr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 270, 25));

        lblMessage11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMessage11.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMessage11.setText("Pharmacy Feedback:");
        kGradientPanel3.add(lblMessage11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        txtAnimalMessageFromPharmacy.setEnabled(false);
        kGradientPanel3.add(txtAnimalMessageFromPharmacy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 270, -1));

        rbtnMale1.setForeground(new java.awt.Color(255, 255, 255));
        rbtnMale1.setSelected(true);
        rbtnMale1.setText("Male");
        rbtnMale1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMale1ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(rbtnMale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        rbtnFemale.setForeground(new java.awt.Color(255, 255, 255));
        rbtnFemale.setText("Female");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });
        kGradientPanel3.add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        add(kGradientPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnMale1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMale1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMale1ActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemaleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel kGradientPanel3;
    private javax.swing.JLabel lblMessage11;
    private javax.swing.JLabel lblMessage12;
    private javax.swing.JLabel lblMessage5;
    private javax.swing.JLabel lblMessage7;
    private javax.swing.JLabel lblMessage8;
    private javax.swing.JLabel lblMessage9;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale1;
    private javax.swing.JTextField txtAnimalMessageFromPharmacy;
    private javax.swing.JTextField txtOrphanAge;
    private javax.swing.JTextField txtOrphanMessageFromDr;
    private javax.swing.JTextField txtOrphanRace;
    private javax.swing.JTextField txtOrphanfName;
    // End of variables declaration//GEN-END:variables
}
